// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace MDM.Models
{
    public partial class Navigation
    {
        public const string Codename = "navigation";
        public const string SortOrderCodename = "sort_order";
        public const string TextCodename = "text";
        public const string LinkUrlCodename = "link_url";

        public decimal? SortOrder { get; set; }
        public string Text { get; set; }
        public string LinkUrl { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}