// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace MDM.Models
{
    public partial class ResourceCard
    {
        public const string Codename = "resource_card";
        public const string CardImageCodename = "card_image";
        public const string ResourceNameCodename = "resource_name";
        public const string ResourceShortDescriptionCodename = "resource_short_description";
        public const string ResourceLinkCodename = "resource_link";

        public IEnumerable<Asset> CardImage { get; set; }
        public string ResourceName { get; set; }
        public string ResourceShortDescription { get; set; }
        public string ResourceLink { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}