// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace KenticoCloudBase.Models
{
    public partial class AssociateProfile
    {
        public const string Codename = "associate_profile";
        public const string AssociateNameCodename = "associate_name";
        public const string AssociateTitleCodename = "associate_title";
        public const string CredentialsCodename = "credentials";
        public const string AssociateStatusCodename = "associate_status";
        public const string AssociateSummaryCodename = "associate_summary";
        public const string DevelopmentExperienceCodename = "development_experience";
        public const string MethodologiesCodename = "methodologies";
        public const string FunctionalBusinessExperienceCodename = "functional_business_experience";
        public const string IndustriesServedCodename = "industries_served";
        public const string AdditionalTechnicalExperienceCodename = "additional_technical_experience";
        public const string ClientFeedbackCodename = "client_feedback";
        public const string ResultsCodename = "results";
        public const string AssociateExperiencesCodename = "associate_experiences";
        public const string EducationCodename = "education";
        public const string CommunityInvolvementCodename = "community_involvement";
        public const string TechnicalAndBusinessSkillsCodename = "technical_and_business_skills";
        public const string CertificationsAndProfessionalMembershipsCodename = "certifications_and_professional_memberships";
        public const string CompleteAssociateProfileCodename = "complete_associate_profile";

        public string AssociateName { get; set; }
        public string AssociateTitle { get; set; }
        public string Credentials { get; set; }
        public IEnumerable<TaxonomyTerm> AssociateStatus { get; set; }
        public string AssociateSummary { get; set; }
        public IEnumerable<TaxonomyTerm> DevelopmentExperience { get; set; }
        public IEnumerable<TaxonomyTerm> Methodologies { get; set; }
        public IEnumerable<TaxonomyTerm> FunctionalBusinessExperience { get; set; }
        public IEnumerable<TaxonomyTerm> IndustriesServed { get; set; }
        public string AdditionalTechnicalExperience { get; set; }
        public string ClientFeedback { get; set; }
        public string Results { get; set; }
        public IEnumerable<object> AssociateExperiences { get; set; }
        public string Education { get; set; }
        public string CommunityInvolvement { get; set; }
        public IEnumerable<TaxonomyTerm> TechnicalAndBusinessSkills { get; set; }
        public IEnumerable<TaxonomyTerm> CertificationsAndProfessionalMemberships { get; set; }
        public IEnumerable<Asset> CompleteAssociateProfile { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}