// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace KenticoCloudBase.Models
{
    public partial class AssociateProfileExperience
    {
        public const string Codename = "associate_profile_experience";
        public const string IndustryCodename = "industry";
        public const string RoleCodename = "role";
        public const string StartDateCodename = "start_date";
        public const string EndDateCodename = "end_date";
        public const string ProductCodename = "product";
        public const string DetailsCodename = "details";

        public string Industry { get; set; }
        public string Role { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Product { get; set; }
        public string Details { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}